class UserNotFoundException(Exception):
    pass

class OrderNotFoundException(Exception):
    pass
